### ISSUE TITLE
Support for CPUs with multiple cores

### ISSUE THREAD

**Issue by pronei** [pesos/grofer#1]
Currently, the CPU usage grid displays the utilization in percentage for each individual logical core but is restricted to dual and quad core processors (with 4 and 8 logical cores assuming that HT is enabled).

A possible solution is to create an array with `termui.NewRow` objects whose width percentages are adjusted according to `numCores`. Unpacking this within the respective column in `mainPage.Grid.Set` should get the job done in theory since it supports variadic parameters.

**Comment by Gituser143** [comment]
@pronei any progress with this? If you're having an issue putting multiple gauges into the grid a fair approach would be to Initialise the gauges outside the grid. You can then have any number of gauges you want initialised and update them accordingly too.

**Comment by pronei** [comment]
Seems good but there's a lot of flickering now. Not sure why though.

This was what I had initially tried but didn't work:
 ```golang
var coreRows []interface{}
coreRows := make([]interface{}, numCores)

for i := 0; i < numCores; ++i {
    coreRows[i] = ui.NewRow(float64(1.0 / numCores), page.CPUCharts[i])
}

page.Grid.Set(
    ui.NewCol(0.54,
        coreRows...,
    ),
    ui.NewCol(0.46,
        ui.NewRow(0.34, page.MemoryChart),
        ui.NewRow(0.34,
            ui.NewCol(0.25, page.NetPara),
            ui.NewCol(0.75, page.NetworkChart),
        ),
        ui.NewRow(0.34, page.DiskChart),
    ),
)
```
I'm pretty new to Go and am quite unfamiliar with how memory allocation works for objects that implement a certain interface.

**Comment by Gituser143** [comment]
@pronei The flickering might be because of the high refresh rates. Maybe try increasing it on a local build?
