### ISSUE TITLE
[FEATURE REQ] Add Dockerfile for `grofer` 

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#101]
**Describe the solution you'd like**
Have a Dockerfile for grofer for ease of use. 
```
docker run pesos/grofer:latest
```

**Additional context**
- On initial thought, this can be done by mounting the file systems being used by `gopsutil` to fetch metrics, `/proc` and `/sys` might be a good starting point.

**Comment by Samyak2** [comment]
I looked this up a bit, haven't tried any of this yet. Apparently, mounting `/proc` inside the container does not provide details of the host. The alternative is to mount the whole root FS as read-only in the container ([ref](https://stackoverflow.com/a/49169257)).

It might be only for the hostname, I'm not sure yet. I can take up this issue if no one else has taken it up for a few days.

**Comment by MadhavJivrajani** [comment]
Ohhh that makes sense, hmm.

Mounting the whole root file system could be an option, maybe qualifying the mount as read only as well.

**Comment by MadhavJivrajani** [comment]
Okay so I did a little digging, [`cAdvisor`](https://github.com/google/cadvisor#quick-start-running-cadvisor-in-a-docker-container) also mounts the entire root file system for this purpose, followed by a read-only qualification. That might be the way to go.

**Comment by MadhavJivrajani** [comment]
@Samyak2 looks like you can take this up!
