### ISSUE TITLE
[FEATURE REQ] Add keybindings for sorting output for `grofer proc`

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#107]
**Is your feature request related to a problem? Please describe.**
As @Gituser143 pointed out, it'd be nice to have sort functionality based on different columns of the `grofer proc` output. 

**Describe the solution you'd like**
`ctrl + 1` for sorting by first column of the output? And so on for the other columns. 

**Describe alternatives you've considered if any**
`shift` was discussed, but `termui` does not have keybindings for that.

**Comment by Gituser143** [comment]
This should probably be done for `grofer container` too. Unsorted tables are annoying :P
