### ISSUE TITLE
[FEATURE REQ] add key bindings for `kill`ing and `restart`ing docker containers from `grofer`

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#108]
**Is your feature request related to a problem? Please describe.**
It'd be cool to `kill` or `restart` containers from the UI of `grofer container`

**Describe the solution you'd like**
`k` to `kill` and `r` to `restart`, implementation should be similar to #54, except for how `kill` and `restart` is sent to the container

**Additional context**
RAGE KILLLLLLLLLLLLLLL

**Comment by anihm136** [comment]
Have you come across https://github.com/jesseduffield/lazydocker? It has a really cool intuitive UI and could give some ideas on how to implement as well (I use the git counterpart, highly recommended btw)

**Comment by Gituser143** [comment]
@anihm136 Yep we're looking for someone similar! I recently tried the same locally by using the same docker SDK, it's essentially just one command to kill/remove containers (doc can be found [here](https://pkg.go.dev/github.com/ph/moby/client#Client.ContainerRemove)). But for some reason it kept freezing my host system. Worked like a charm on a virtual machine though.
