### ISSUE TITLE
[BUG] grofer fails in tmux

### ISSUE THREAD

**Issue by anihm136** [pesos/grofer#114]
**Describe the bug**
When trying to run grofer in a tmux session, it fails with the following error -
```
Error: failed to initialize termui: termbox: error while reading terminfo data: termbox: unsupported terminal
```

**To Reproduce**
1. Start a new tmux session
2. Run grofer

**Expected behavior**
Grofer should not fail in tmux (or failure should be documented)

**Desktop (please complete the following information):**
 - OS: Linux 5.12.3-arch1-1 x86_64 GNU/Linux
 - Go Version: 1.16.4

**Additional context**
The issue appears to be with the termui library. If so, we should look for a solution upstream, document the failure and maybe look for a workaround if a solution is not available

**Comment by Samyak2** [comment]
It works for me, in tmux too. I use [oh my tmux](https://github.com/gpakosz/.tmux) for my tmux config, it could be due to that.

Also, from the error it seems like an issue with the terminal which I'm assuming it infers from `$TERM`. `echo $TERM` gives `screen-256color` for me. Maybe try setting that manually?

**Comment by Samyak2** [comment]
I think this can confirm that it's due to `$TERM`

```
❯ TERM=somerandomterminal ./grofer
zsh: can't find terminal definition for somerandomterminal
Error: failed to initialize termui: termbox: error while reading terminfo data: termbox: unsupported terminal
```

**Comment by anihm136** [comment]
Hmmm. I haven't changed my default terminal for tmux, so it is set to `tmux-256color`. This appears to be an upstream issue

**Comment by anihm136** [comment]
Running grofer with `TERM=xterm-256color grofer` works on tmux. Possible addition to docs/FAQ, since this is a common fix for all terminfo entries not supported by termui
