### ISSUE TITLE
[BUG] Incorrect unit in `RoundValues()`

### ISSUE THREAD

**Issue by Gituser143** [pesos/grofer#118]
**Describe the bug**
In the `utils` package, the `RoundValues()` function has a small error where the switch case classifies units as `per thousand`, `per million` and **`per trillion`**. Additionally, no default case is set, which could lead to the function returning empty values.

**To Reproduce**
Unsure how to reproduce.

**Expected behaviour**
The third unit must be `per billion` and not `per trillion`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Go Version 1.16

**Comment by mihirkestur** [comment]
Greetings! Can i work on this?

**Comment by MadhavJivrajani** [comment]
Absolutely! I'll assign it to you :)
