### ISSUE TITLE
The CPU data visualization is not rendered properly 

### ISSUE THREAD

**Issue by nsankethreddy** [pesos/grofer#13]
# The visualization of the CPU data is rendered out of the screen

**To Reproduce**
(I use a 2 core 4 CPU system)
1. Go to ... /grofer/
2. Build the grofer code ```go build grofer.go```
3. Execute the newly created executable ```./grofer```

**Expected behavior**
All the widgets to be rendered in the screen

**Screenshots**

![Screenshot from 2020-08-04 17-45-04](https://user-images.githubusercontent.com/47980147/89293341-67dbc900-d67b-11ea-9c4d-fc0c834ca681.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Go Version:version go1.14.4 linux/amd64

**Comment by Gituser143** [comment]
Changed `height := int(h / (numCores - 1))` to `height := int(h / numCores)` in overallGraphs.go to resolve issue
