### ISSUE TITLE
Major memory leak: `grofer proc -p` on processes having RSS value of zero

### ISSUE THREAD

**Issue by tfidfwastaken** [pesos/grofer#17]
**Describe the bug**
Running `grofer proc -p <pid>` on any process that has RSS zero (usually all kernel processes seem to have RSS zero, along with stuff like some zombie processes) will cause a memory leak, which will rapidly fill up memory and freeze your device.

**To Reproduce**
1. Run `top` 
2. Identify the PID of any process having RSS as 0
3. Run ` grofer proc -p <PID>`
4. Watch your device die before your very eyes

**Expected behavior**
Display the stats without ideally dying.

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04
 - Go Version: 1.14.6

**Comment by MadhavJivrajani** [comment]
This seems to be happening due to a bug in termui's [code](https://github.com/gizak/termui/blob/master/v3/widgets/barchart.go)

maxVal fetched in the case of an idle kernel process will still be 0 and that'll cause all types of divide by zero errors but since UI is constantly rendering, those errors aren't coming up

**Comment by tfidfwastaken** [comment]
Oh wow so this is an upstream error?

**Comment by MadhavJivrajani** [comment]
Yes. I'll send a PR to termui but it doesn't look like the codebase is maintained anymore. 

Worst case we'll fork it and make the necessary changes and use that as the upstream dependency

**Comment by tfidfwastaken** [comment]
Are you sure it is just the zero values?

When I hardcode 1.0 for all values in `memData` in the file `procGraph` I still am facing this problem.
