### ISSUE TITLE
Make overall stats into a struct type

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#2]
For cleaner and more maintainable code, would it be possible to make all the stats being rendered by the `grofer` command into a single struct type so that a new channel does not have to be created for every new type of metric being displayed? Only two channels can be passed to the `RenderCharts` function, `endChannel` and `dataChannel` and all functions that update these metrics could be part of a struct method. So it could look something like this:

```go
// Metrics struct comment
type Metrics struct {
	memInfo  []float64
	diskInfo [][]string
	cpuInfo  []float64
	netInfo  map[string][]float64
}

// Update function comment
func (m *Metrics) Update() {
     ...
}
```

**Comment by Gituser143** [comment]
Although this might provide readability, it'll introduce heavy delays right? Because we'd have to update all metrics and then send it. What we're doing now is getting all metrics on separate routines and each of these routines communicates with the UI widget using a distinct channel.

**Comment by MadhavJivrajani** [comment]
Hmm, that makes sense, but the functions that are in goroutines are formatting the information that was _sequentially_ fetched in the `GlobalStats` function. If more stats are added, it might be infeasible to continuously keep creating new channels for each metric

**Comment by Gituser143** [comment]
I see what you mean, as of now we could optimize the fetching of metrics by placing them in the functions that send them, but that wouldn't solve the issue of sending data through different channels. Maybe we could use a single channel for all the data and differentiate which widget they belong to on the receiving end?

**Comment by MadhavJivrajani** [comment]
Hmm yeah that would be feasible, maybe a channel fo type `{}interface` as you mentioned and send structs with one field indicating which metric it belongs to

**Comment by Gituser143** [comment]
If we're using a struct might as well make the channel of that type right?

**Comment by MadhavJivrajani** [comment]
If we're using a single data channel for communication, assuming we use a struct to differentiate the widget the data belongs to, data types of the fields of structs will differ right?

**Comment by Gituser143** [comment]
That can be handled easily I feel, if we use a struct like the one mentioned here: 
```go
// Metrics struct comment
type Metrics struct {
	memInfo  []float64
	diskInfo [][]string
	cpuInfo  []float64
	netInfo  map[string][]float64
        fieldSet int
}

// Update function comment
func (m *Metrics) Update() {
     ...
}
```
We can send the struct with only one of the field values set and the variable `fieldSet` to a unique number which identifies the field. This way we just check the integer value set and extract from the specific field.

**Comment by MadhavJivrajani** [comment]
Oh peace, that'll work great
