### ISSUE TITLE
Library Migration

### ISSUE THREAD

**Issue by siddhantrao23** [pesos/grofer#30]
**Is your request related to a problem? Please describe.**
Running `grofer` on certain terminal dimensions causes the Network and Memory graphs to go past the widget borders. This is most likely a bug in [termui](https://github.com/gizak/termui), which is no longer maintained.

**Describe the solution you'd like**
Migrating to another library like [termdash](https://github.com/mum4k/termdash) would be one possible solution, which has cleaner looking widgets and could prove to be better for future applications. Further discussion on compatibility and ease of migration is required. A new branch could be created for this migration. 

**Screenshots**
![issues](https://user-images.githubusercontent.com/44816445/89521094-85846c00-d7fc-11ea-9e92-79fb055e5c97.png)

**Desktop (please complete the following information):**

* OS: Kubuntu 18.04
* Terminal: konsole 17.12.3
* Go: 1.14.6

**Comment by MadhavJivrajani** [comment]
Refer #31
