### ISSUE TITLE
[FEATURE REQ] Add functionality to export data to JSON/CSV.

### ISSUE THREAD

**Issue by Gituser143** [pesos/grofer#33]
**Is your feature request related to a problem? Please describe.**
As of now we only display stats through the UI, exporting these to a file in the format of JSON, CSV, etc., will be extremely useful.

**Describe the solution you'd like**
A functionality where running `grofer export [ --type=JSON ] [ --iter=100 ] [ --interval=500 ] FILE` would export stats over a specified number of iterations over given intervals into a specific file format.

**Comment by MadhavJivrajani** [comment]
I've created a project board for this feature, feel free to close this issue and create and add issues related to the `export` command to the `grofer export` project board!

**Comment by MadhavJivrajani** [comment]
Development for `export` feature is being done on the `export` branch ([link](https://github.com/pesos/grofer/tree/export))
