### ISSUE TITLE
[FEATURE REQ] Tab completion for grofer.

### ISSUE THREAD

**Issue by Gituser143** [pesos/grofer#39]
**Is your feature request related to a problem? Please describe.**
The grofer command would be easier to use with tab completion!

**Describe the solution you'd like**
As we're implementing cobra to parse command line options and arguments, we could enhance it with tab auto completions as cobra supports this for major shells.

**Comment by anihm136** [comment]
From what I read, `cobra` has a utility for generating a `go` file, which provides the executable with an option to generate an autocompletion script for various shells. Once generated, it would have to be moved to an appropriate location (on the user's `fpath` in Linux) for it to be used. How would we handle moving the generated completion script onto `fpath`?

**Comment by anihm136** [comment]
Can I pick this up? (I kinda got confused and mixed up the issue I was working on :sweat_smile:)

**Comment by Gituser143** [comment]
@anihm136 Sure! I'll assign you to the same.
