### ISSUE TITLE
Add directions to all the channels in the function signatures taking channel

### ISSUE THREAD

**Issue by tfidfwastaken** [pesos/grofer#4]
**Description**
In many functions, for example the two shown below, the channel data only flows in one direction.
https://github.com/pesos/grofer/blob/0c781a2c09128fe456a077781dcffa2d7513a208/src/general/generalStats.go#L31
https://github.com/pesos/grofer/blob/0c781a2c09128fe456a077781dcffa2d7513a208/src/graphs/overallGraphs.go#L120
For example, in `GlobalStats` , `endChannel` only has its data flowing out of the channel (ie `<-endChannel`) and the other channels only receive data (ie `cpuChannel <-`).

Since the data only flows into one channel, we can make the types stricter in the function definition by having the channel direction specified, thus increasing type safety of the program.

Reference for how to do this: https://gobyexample.com/channel-directions

**Deliverable in the PR**
- [ ] Identify all the functions where the channels only need to flow in a single direction
- [ ] Specify the directions of the channels in the function signature
- [ ] Make sure the program passes all tests (which have not been implemented yet, so for the time being ensure the program still runs correctly before submitting your PR)

**This issue is for `first-timers-only`, that is, we are only going to accept your PR if you have never made a code contribution before.**

**Comment by Gituser143** [comment]
@tfidfwastaken This isn't what's quite happening. You're not taking channel messages as arguments. If we end up doing so the program won't work for the simple reason that the argument itself will be a block, the code won't proceed. And if data does come in, the program exits. 

It'll break the program is what I think.

**Comment by tfidfwastaken** [comment]
Oh right my bad :p 

I had written this one down before I fully understood how you are doing the channel thing here. 

Thanks for clarifying. I think this should be closed.

**Comment by Gituser143** [comment]
Will wait for @MadhavJivrajani or @metonymic-smokey to confirm before closing.

**Comment by MadhavJivrajani** [comment]
Go ahead
