### ISSUE TITLE
[BUG] `grofer about` is heart broken

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#41]
**Describe the bug**
The ♥ in the `grofer about` does not display fully.

**To Reproduce**
Run `grofer about`

**Screenshots**
![Screenshot_20200812_231622](https://user-images.githubusercontent.com/12381034/90049053-ec6cbe00-dcf1-11ea-92da-d00d3547e4c9.png)

**Expected behavior**
![Screenshot_20200812_231849](https://user-images.githubusercontent.com/12381034/90049283-36ee3a80-dcf2-11ea-8a52-6c45bc3b76c1.png)

**Desktop (please complete the following information):**
 - OS: kubuntu 20.04
- Terminal: konsole
 - Go Version 1.14.7

**Additional context**
halp

**Comment by AbhilashBalaji** [comment]
running on MacOS iterm2 and zsh with a powerline font (fira code),
<img width="627" alt="fira code" src="https://user-images.githubusercontent.com/29544273/91653798-660df580-eac1-11ea-9417-cac3d6083f3a.png">
 seems fine

heres comic sans :)))
<img width="627" alt="comic sans" src="https://user-images.githubusercontent.com/29544273/91653824-99508480-eac1-11ea-9f65-88e915982133.png">

so it doesnt seem to be a PowerLine glyph thing also , any other suggestions on recreating the issue ?

**Comment by MadhavJivrajani** [comment]
A lot of people seem to have this issue with re-creating it, maybe it's just on my laptop.

Terminal: Konsole
Font: Hack
Font size: 15 pt

Maybe this might help

**Comment by Samyak2** [comment]
> Terminal: Konsole
> Font: Hack
> Font size: 15 pt

I can't reproduce it even with the same terminal, font and font size.

**Comment by MadhavJivrajani** [comment]
Wow, that's weird :exploding_head:
