### ISSUE TITLE
[BUG] allignment in list of child processes in `grofer proc -p PID` is not consistent.

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#45]
**Describe the bug**
The alignment in the table for the list of child processes of a process is not consistent. I'm assuming this is happening due to the varying lengths of PID. 

**To Reproduce**
Run `grofer proc -p 1` and hit the `↓` key a few times.

**Expected behavior**
Alignment remains consistent irrespective of the length of the PID. 

**Screenshots**
![Screenshot_20200819_231213](https://user-images.githubusercontent.com/12381034/90671144-e89ce680-e271-11ea-9e74-8f32790028c8.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Go Version: 1.14.7
- Terminal: Konsole

**Additional context**
Should be fixable by looking at the code in the `getChildProcs` function in the file `src/display/process/procGraphs.go`

**Comment by siddhant94** [comment]
hey @MadhavJivrajani , I would like to take it up if it's unassigned.

**Comment by Gituser143** [comment]
Hey @siddhant94, feel free to start! I'll assign you to this issue.

**Comment by siddhant94** [comment]
Hey @MadhavJivrajani @Gituser143 , any guidelines as how to submit PR for this? Shall I fork it and mark your repo as upstream and then raise a PR? The solution I have implemented is
```
func getChildProcs(proc *process.Process) []string {
	headerString := "PID" + strings.Repeat(" ", 19) + "Command"
	childProcs := []string{headerString}
	for _, proc := range proc.Children {
		var processData, spacesForCommandRowData string
		processPid := strconv.Itoa(int(proc.Pid))
		// 22 reflects position where row data for "Command" column should start (headerString has 19 spaces + length of ("PID") is 3 i.e. 22)
		spacesForCommandRowData = strings.Repeat(" ", 22-len(processPid))
		exe, err := proc.Exe()
		if err == nil {
			processData = processPid + spacesForCommandRowData + "[" + exe + "](fg:green)"
		} else {
			processData = "["+processPid+"](fg:yellow)" + spacesForCommandRowData + "NA"
		}
		childProcs = append(childProcs, processData)
	}
	return childProcs
}
```

**Comment by MadhavJivrajani** [comment]
Hi @siddhant94, 
Yes, please go ahead and open a PR by making changes in your fork, please make sure you've read the [contributing guideline](https://github.com/pesos/grofer/blob/master/CONTRIBUTING.md) and if you need any further help please feel free to let us know. 

The changes you suggested, I'll be able to validate them only once you send in your PR. But it looks good to me for the most part! :smile:

**Comment by siddhant94** [comment]
> Hi @siddhant94,
> Yes, please go ahead and open a PR by making changes in your fork, please make sure you've read the [contributing guideline](https://github.com/pesos/grofer/blob/master/CONTRIBUTING.md) and if you need any further help please feel free to let us know.
> 
> The changes you suggested, I'll be able to validate them only once you send in your PR. But it looks good to me for the most part!

Done. Raised a PR - https://github.com/pesos/grofer/pull/61
