### ISSUE TITLE
[BUG] High CPU utilisation

### ISSUE THREAD

**Issue by Samyak2** [pesos/grofer#5]
**Describe the bug**

`grofer proc` takes anywhere between 40-60% of a CPU core (measured using `grofer proc -p $(pidof grofer)` ). Looking through `htop`, the usage seems even higher, there are multiple grofer proc processes (5+) with two of them taking 60+10% CPU.

`grofer` uses 15-20% of a CPU core (again, measured through `grofer proc -p $(pidof grofer) `). htop reports the CPU usage to be 25%+.

**To Reproduce**

1. Open `grofer proc` in one terminal
2. In another terminal, do `grofer proc -p $(pidof grofer)`
3. Notice high CPU usage

**Expected behavior**

The profiler itself should not consume too much CPU power. Ideally, less than 5% seems good.

**Screenshots**

![CPU usage as seen through grofer](https://user-images.githubusercontent.com/34161949/89201649-75d41000-d5cf-11ea-88bd-54ee6e5ca41f.png)
![CPU usage seen through htop](https://user-images.githubusercontent.com/34161949/89201716-8d12fd80-d5cf-11ea-8386-6e2a88fd31a2.png)

**Desktop (please complete the following information):**

 - OS: Fedora 32
 - Go: 1.14.6

**Additional context**

Could be solved by reducing the delay/interval to be around 1s.

**Comment by Gituser143** [comment]
@Samyak2 @siddhantrao23 The last few commits to master made an attempt to lower CPU consumption for `grofer proc -p PID`, it also significantly lowered CPU for `grofer`. If you have any update or ideas for fixes, please update here too.
