### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by tfidfwastaken** [pesos/grofer#6]
**Describe the bug**
The lack of automated tests is a big deal, given that we are going to have a lot more external contributions. We need to add a good amount of tests that cover most of the code and also add a GitHub Actions workflow that runs those tests every time a PR is made, so that we do not have to worry about new commits breaking existing functionality. Passing tests should be a minimum requirement to merge a PR.

Moreover it should be a requirement that new functionality must also include tests for the same, wherever feasible.

I do not yet know about the testing facilities in Go, but I can help with setting up the CI workflow, once we get some tests added.

**Comment by tfidfwastaken** [comment]
Removing the `good-first-issue` for the time being. It will be that only once the testing framework is decided upon and the first few tests are already written.

**Comment by MadhavJivrajani** [comment]
I'll write a few basic tests to get us started on setting up a testing pipeline

**Comment by Gituser143** [comment]
Added Travis CI tests for building and Go formatting
