### ISSUE TITLE
[REFACTOR] Small changes needed to increase code readability and maintainability.

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#64]
Small amounts of refactoring can be done to all files under `cmd` which have additional flags.

## Creating `const` types for default values of flags.
- Each flag in [cobra]() needs to have a default value set. As of now the default value in some cases is mentioned while creating the flag such as https://github.com/pesos/grofer/blob/03a98094cd2fd6b8822d0295f0e38e230e5ee730/cmd/proc.go#L106

- For increased readability and also maintainability, it would be better to have a `const` of these default values like [this](https://github.com/pesos/grofer/blob/03a98094cd2fd6b8822d0295f0e38e230e5ee730/cmd/proc.go#L31):
```go
const (
	DefaultProcRefreshRate = 3000
)
```

## Splitting flag initialization to multiple lines

A flag initialization such as:
```go
procCmd.Flags().Int32P("refresh", "r", DefaultProcRefreshRate, "Process information UI refreshes rate in milliseconds greater than 1000")
```
could be re-written to:
```go
procCmd.Flags().Int32P(
    "refresh",
    "r",
    DefaultProcRefreshRate,
    "Process information UI refreshes rate in milliseconds greater than 1000",
)
```

**Comment by souvikmaji** [comment]
I am picking this up.

**Comment by MadhavJivrajani** [comment]
Sure.
