### ISSUE TITLE
[ENHANCEMENT] change type of `refreshRate` and `pid` flag to unsigned int

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#65]
- In `cmd/proc.go` and `cmd/root.go` the type of the `refreshRate` flag is an `int32`.
- In `cmd/proc.go` the type of PID is `int32`.

In both these cases, I feel like it would be better to keep the type to unsigned integers as the values can never be allowed to be negative. 

- `int32` for `refreshRate` could be changed to `uint64` to handle the case of an extremely large refresh rate since refresh rate is to be provided in milliseconds. 
- `int32` of `pid` could be changed to `unit32`.
    - The default value of PID could be changed to 0.

To be solved after #64

**Comment by souvikmaji** [comment]
Picking this one up also.

**Comment by prncvrm** [comment]
picking up this!

**Comment by prncvrm** [comment]
https://github.com/pesos/grofer/pull/68

**Comment by souvikmaji** [comment]
@prncvrm LOL, don't rush to add an incomplete PR to an issue, which someone has already started working and commented so also.

**Comment by MadhavJivrajani** [comment]
Hi guys,
As a general good practice, its always recommended that you ask if an issue is available to be worked on and if so, whether you can work on it, rather than declaring that you will be working on this. As far as I can tell, both of you commented in the same manner at more or less the same exact time, there's no real way to decide this. 

In order to try and be as fair as possible to you guys, we will be closing the PR by @souvikmaji for this issue since he has already contributed to this repo (this is done because there's a conflict in terms of whose PR should be accepted). But @souvikmaji's PR is valid too and that's why we'll be adding the `hacktoberfest-accepted` to it so that it counts towards hacktoberfest even though it is closed. 

And one last thing, *please* follow the PR template. It is extremely important that you do so. The only reason that we'll be considering @prncvrm's PR is that it is borderline acceptable in terms of the issue it is solving, but bear in mind to follow templates and contribution guidelines.

**Comment by prncvrm** [comment]
@MadhavJivrajani thanks. @souvikmaji i really didn't see your comment back then. its less than a 1 min diff btwn our comments 👍
