### ISSUE TITLE
[BUG] Under white background the texts are not visible properly

### ISSUE THREAD

**Issue by souvikmaji** [pesos/grofer#66]
**Expected behavior**
Based on the background color of the terminal, text color scheme should change. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5869648/95007304-e0cfb080-062b-11eb-87bd-0925e73c6e1f.png)

**Desktop:**
 - OS: Linux Mint
 - Go Version: 1.14.3
 - Mate Terminal

**Comment by MadhavJivrajani** [comment]
CC @Gituser143

**Comment by panzerox123** [comment]
Hey! I'd like to work on this issue!

**Comment by Gituser143** [comment]
Have at it @panzerox123 !
