### ISSUE TITLE
[BUG] High exit time

### ISSUE THREAD

**Issue by Samyak2** [pesos/grofer#75]
**Describe the bug**

`grofer` or `grofer proc` takes a few seconds to exit to the shell prompt after pressing `q` or `ctrl-c`.

The time taken to exit increases as the refresh time is increased.

**To Reproduce**

1. Run `./grofer -r 10000` in a terminal
2. Exit grofer using `q` or `ctrl-c`
3. Notice time taken for the shell prompt to reappear

**Expected behavior**

The process should exit immediately after `q` or `ctrl-c` is pressed.

**Screenshots**

![image](https://user-images.githubusercontent.com/34161949/95593263-15e26580-0a67-11eb-920d-0685b3c225b3.png)

**Desktop (please complete the following information):**
 - OS: Fedora 32 KDE
 - Go Version: v1.14.9

**Additional context**

[This comment in #54](https://github.com/pesos/grofer/pull/54/#issuecomment-706170043)

**Comment by MadhavJivrajani** [comment]
On investigating a little, the problem seems to occuse because of this line:
https://github.com/pesos/grofer/blob/5e9d902f56595d407529d3bde056c7a636613f9b/src/general/generalStats.go#L67

**Comment by ataboo** [comment]
May I take a look at this one?

**Comment by MadhavJivrajani** [comment]
Absolutely! Have at it :smile:

**Comment by Gituser143** [comment]
@ataboo Thanks for the fix!
