### ISSUE TITLE
[BUG] Increased refresh rate time due to data fetch and serve delays.

### ISSUE THREAD

**Issue by Gituser143** [pesos/grofer#78]
**Describe the bug**
Currently although UI is refreshed at given refresh rate, data being fetched and sent to UI is slower. Functions that serve the data take time to fetch data and then sleep for the given refresh rate. This causes a visible delay in the UI.

**To Reproduce**
1. build grofer `go build grofer.go`
2. run `./grofer -r 1000`
3. Notice fields being updated in intervals much larger than 1 second.

**Expected behavior**
The functions serving data should consume a total of "refresh rate" amount of time to fetch, send data and sleep (1 cycle). This could be fixed by checking time consumed in fetching and serving data, and then reducing sleep time accordingly. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Go Version 1.14.2

**Comment by akashgupta05** [comment]
I'd like to pick up this issue. please assign it to me.

**Comment by MadhavJivrajani** [comment]
Sure! Looking forward to your PR 😄

**Comment by Gituser143** [comment]
@akashgupta05 please take not of #77 as it might involve some changes that might affect what you plan to change. If necessary, feel free to wait for the above to merged.

**Comment by akashgupta05** [comment]
Thanks, i will make sure to raise PR without any conflict in files and issues in solution.

**Comment by Gituser143** [comment]
Hey @akashgupta05, looks like the PR #77 fixed the delay issue too. A ticker was implemented to ensure exit times are immediate, but since this was started before corresponding calls to serve data, it does not wait for the overhead of the fetch and serve delays. 

I'm sorry, but we will be closing this issue. If you'd like to pick up any other issue, we'd be happy to assist!
So sorry for the inconvenience.
