### ISSUE TITLE
[FEATURE REQ] provide support for different signal types

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#80]
**Is your feature request related to a problem? Please describe.**
`gopsutil` provides [support](https://godoc.org/github.com/shirou/gopsutil/process#Process.SendSignal) for 4 different types of signals that can be sent to a process, signals other than these 4 need to be implemented such as `SIGABRT`. A list of signals can be obtained by running `kill -l`

**Describe the solution you'd like**
Maybe the implementation of sending signals could be done using the [`Signal()`](https://godoc.org/os#Process.Signal) function.

**Comment by Samyak2** [comment]
Do these have to be implemented in separate functions (such as `sendHup`, `sendInt`) or a general function to send a given signal to a process?

**Comment by MadhavJivrajani** [comment]
Separate functions can be implemented to send individual signals, but only a single exposed interface should preferably be available. We could have codes for each type of signals as consts and a `map` from these consts as keys and values as functions. Maybe we could get the function from the `map` and then call it, handle errors from it, etc.

**Comment by anihm136** [comment]
I can try this. syscall already has aliases for all kinds of signals, which can be passed directly to Signal(). Do you think it's a good idea to forego gopsutil entirely for this functionality to maintain a uniform implementation?

**Comment by MadhavJivrajani** [comment]
Yep! That would be ideal. Go for it!

**Comment by anihm136** [comment]
Quick update, I've started work on this. `gopsutil` has a `SendSignal` method that takes an arbitrary signal as defined by `syscall` and sends it to a process. I'm planning to use it for further work on this
