### ISSUE TITLE
[BUG] incorrect pid validation in `proc` command

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#86]
**Describe the bug**
`grofer proc -p [PID]` should give an error when an invalid PID is entered (negative values and some cases 0 as well as 0 might indicate the `sched` or the `swapper` process), if a PID equal to the `defaultProcPid` is entered, it runs the `grofer proc` command which shows info about all processes. 

**To Reproduce**
`grofer proc -p -1`

**Expected behavior**
The error shows for PID 0 and other negative numbers other than -1 should be shown for PID = -1 as well. 

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Go Version 1.14.7

**Additional context**
Looking at `cmd/proc.go` should help!

**Comment by Samyak2** [comment]
I had a go at this (pun intended), but I couldn't find a good enough solution.

I looked for ways to [check if a flag was set explicitly](https://stackoverflow.com/questions/54379749/how-do-i-extract-only-flagsets-that-are-being-set-explicitly-in-the-cli), tried the [`pflag` functions which use pointers](https://pkg.go.dev/github.com/spf13/pflag#Int32VarP), but neither of the solutions worked.

One solution that can be reasonable is setting `defaultProcPid = math.MinInt32` which works for negative values unless someone tries `grofer proc -p -2147483648` xD. If you think this is good enough, I can send a PR.

**Comment by MadhavJivrajani** [comment]
Yeah, that's the only thing I could think of as well. 

There are a couple of other things that we could consider:
- The way `top` does it is that if you give a PID of 0, it'll run the monitoring of its own PID and any negative value throws an error. So what we could maybe do is, we could change the default to 0 and if the entered PID is 0, we run `grofer proc`, if its anything negative, it'll be caught by the the `NewProcess()` function. 

Another thing is, the way `htop` does it: it won't throw any error in any case, it'll just show the general cpu usage with the process area of the screen empty.

**Comment by Samyak2** [comment]
The `top` way of doing it looks better, but what if `0` is a valid PID?

I would still prefer making `-2147483648` the default value as it allows PID 0 as well as shows errors on common negative values.

**Comment by MadhavJivrajani** [comment]
Afaik `0` won't be a valid PID, its meant for `sched` in linux/unix and windows idle process in windows based systems. Processes like `sched` can't be monitored since they completely exist in the kernel space and forks the `init` process and just runs an infinite loop making sure that there is always a process that the scheduler can schedule and `/proc` doesn't have an entry for it as well so there's no way for getting resource usage info about these PIDs as `gopsutil` depends on `/proc` heavily. 

Using `minInt32` would also work, but for some reason if the user decides to enter that as the PID for whatever reason, having `grofer proc` show up when all other negative PIDs throw errors might be a little inconsistent

**Comment by MadhavJivrajani** [comment]
If that seems okay to you, feel free to send in a PR whenever!

**Comment by Samyak2** [comment]
Ah okay, I did not know that.

Then yes, making 0 the default seems like the better way.
