### ISSUE TITLE
Optimize data fetch from gopsutil

### ISSUE THREAD

**Issue by Gituser143** [pesos/grofer#9]
Currently functions in generalStats.go just format and send data to the UI (`PrintCPURates()`, `PrintMemRates()`, `PrintDiskRates()`). Although they run concurrently, the data fed to these functions are fetched sequentially.

This can be made better by getting the data from within these functions itself and adding subsequent sleeps after all functions are called. 

To then limit rate of influx of data into the UI, we can add small delays between subsequent data fetches using `time.Sleep()`.

**Comment by akeni** [comment]
Hi,

Can you explain what you want to make more efficient? From what I see, the get functions are called in an Async function and then the data is printed sequentially. You want to add a sleep function after the async functions are finished?

**Comment by Gituser143** [comment]
```go
cpuUsageRates, err := cpu.Percent(time.Second, true)
			if err != nil {
				log.Fatal(err)
			}

			memoryStat, err := mem.VirtualMemory()
			if err != nil {
				log.Fatal(err)
			}

			partitions, err := disk.Partitions(false)
			if err != nil {
				log.Fatal(err)
			}

			netIO, err := net.IOCounters(false)
			if err != nil {
				log.Fatal(err)
			}

			go PrintCPURates(cpuUsageRates, cpuChannel)
			go PrintMemRates(memoryStat, memChannel)
			go PrintDiskRates(partitions, diskChannel)
```
@akeni here you can see that the stats are first fetched sequentially from the `gopsutil` functions. The Print functions are concurrent but all they do is format the data and then send them onto the corresponding channel. A better approach would be to fetch the data inside the respective print functions itself. 

This would avoid the sequential fetching of data and in theory speed up the fetches.
