### ISSUE TITLE
-c flag throws error

### ISSUE THREAD

**Issue by RaghavRoy145** [pesos/grofer#97]
**Describe the bug**
mpstat binary not installed by default.
-c flag throws error "Error: exec: "mpstat": executable file not found in $PATH"

**To Reproduce**
1. Open terminal (shell used: zsh 5.8)
2. Command: grofer -c
3. See error: "Error: exec: "mpstat": executable file not found in $PATH"

**Expected behavior**
Show Info about the CPU Load over all CPUs

**Desktop:**
 - OS: Ubuntu 20.10 x86_64
 - Go Version: 1.14.7

**Comment by MadhavJivrajani** [comment]
Thanks for raising this issue!

I think we can try and get information about interrupts from the `/proc` or the `/sys` subsystems. The CPU% information should be provided by `gopsutil`. 

I haven't personally checked this out in depth, but to anyone who might be interested in taking this up, [this](https://github.com/prometheus/procfs) might be a good place to start.

**Comment by panzerox123** [comment]
Hey, could I take this up?

**Comment by Gituser143** [comment]
@panzerox123 Absolutely! I'll assign this to you.
