### ISSUE TITLE
[FEATURE REQ] add the `s`(pause) key-binding to help menus

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#98]
- `grofer` commands that use a UI implement a `s` key-binding which pauses the UI and subsequently pressing `s` again resumes it.
- Currently, when a terminal UI based `grofer` command is running, hitting the `?` brings up the help menu for key-bindings of that command. 
    - The `s` key-binding seems to me missing, and should be added. 

Relevant files:
- https://github.com/pesos/grofer/tree/master/src/display/

**Comment by anirudhRowjee** [comment]
Hi! I'd like to work on this.

**Comment by Gituser143** [comment]
Sure! I'll assign this to you!
